# example YAML for multi-motion-pattern inference
global_seed: 42
output_dir: <results_dir>
pretrained_model_path: <sd1.5_path>
motion_module_path: <AnimateDiff_path>/Motion_Module/v3_sd15_mm.ckpt
unet_checkpoint_path:
  - <ckpt_1>
  - <ckpt_2>

use_ip_adapter: False
ip_ckpt: <IP-Adapter_path>/ip-adapter-plus_sd15.bin
image_encoder_path: <CLIP_image_encoder_path>/image_encoder

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : true

  use_ca_lora: true
  ca_lora_rank: [32,32]
  ca_lora_scale: [1,1]

  adapter_weights: [0.5, 0.5]
  q_downsample: true
  q_downsample_ratio: 1
  ca_pe_mode: rope_3d

  parallel_mode: residual # weights / residual

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : true
    lora_rank: 32
    lora_scale: 1

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false
  # rescale_betas_zero_snr: true


validation_data:
  image_path: <input_images_path>
  prompt_path: all
  batch_prompt: # prompt for each adapter; will be applied to every input image
    - "waterfall"
    - "clouds"
  video_length: 16
  width: 512
  height: 320
  num_inference_steps: 50
  guidance_scale: 1
  use_inv_latent: False
  num_inv_steps: 50

  multi_ca: true # set to True under multi-adapter (with CA-LoRA)

  # initial noise setting
  # Shared noise by LAMP
  shared_noise_ratio: 0.05
  # DCTInit
  first_frame_cond_type: cinemo
  use_dct_init: true

  # post-processing
  use_adain_norm: last # AdaIN mode: on/off/last

  hist_match: false

  # dct_cutoff_shape: tri
  # dct_cutoff_ratio: 0.3

  # word_to_replace:
  #   - "waterfall"
  #   - "clouds"